# Generated by Django 5.0.6 on 2024-06-05 12:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensereport',
            old_name='employee',
            new_name='user',
        ),
        migrations.AddField(
            model_name='expensereport',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=datetime.datetime.now, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensereport',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 17, 33, 37, 390131)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='expenses.expensereport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
